fix start

diff --git a/template b/template
--- a/template
+++ b/template
@@ -43,6 +43,11 @@ start() {
         1>>"$stdout_log" 2>>"$stderr_log" sudo -- $cmd &
         mypid="$!"
     fi
+    echo "$mypid" > "$pid_file"
+    if ! is_running; then
+        echo "Unable to start, see $stdout_log and $stderr_log"
+        exit 1
+    fi
 }
 
 stop() {
